# Note: autogenerated from the original bash script releng/patch_version.sh
# Get the tag and its first annotation line for this commit, if any
$tagInfo = git tag -n --points-at HEAD

if (-not [string]::IsNullOrWhiteSpace($tagInfo)) {
    # --- CASE 1: Tag exists on the current commit ---
    Write-Output "INFO: Found tag on current commit. Using it for version info."

    # Split the tag info string "3.0.0b1 ReleaseName" into version and release
    $version, $release = ($tagInfo -split ' ', 2).Trim()

    # If the tag has no annotation, default to "1" for PEP 440 style
    if ([string]::IsNullOrWhiteSpace($release)) {
        $release = "1"
    }
} else {
    # --- CASE 2: No tag on the current commit ---
    Write-Output "INFO: No tag found on current commit. Creating development version."

    # Find the most recent tag on this branch. Suppress errors if no tags exist.
    $mostRecentTag = git describe --tags --abbrev=0 2>$null
    
    # Get the current UTC timestamp in yyMMddHHmmss format
    $timestamp = (Get-Date).ToUniversalTime().ToString('yyMMddHHmmss')

    if (-not [string]::IsNullOrWhiteSpace($mostRecentTag)) {
        # Construct version from the most recent tag and the timestamp
        $version = "${mostRecentTag}.dev${timestamp}"
    } else {
        # Fallback if no tags exist in the repo's history at all
        Write-Warning "No ancestor tags found. Using '0.0.0' as base."
        $version = "0.0.0.dev${timestamp}"
    }
    
    # Construct the development release name
    $release = "dev-${timestamp}"
}

# --- Perform substitution with the determined version and release ---
if ((-not [string]::IsNullOrWhiteSpace($version)) -and (-not [string]::IsNullOrWhiteSpace($release))) {
    
    Write-Output "Setting version to '$version' and release to '$release'"

    # Define template and destination files
    $filesToPatch = @{
        ".\releng\version-tmpl.py"                  = ".\graxpert\version.py";
        ".\releng\GraXpert-macos-x86_64-tmpl.spec" = ".\GraXpert-macos-x86_64.spec";
    }

    foreach ($template in $filesToPatch.Keys) {
        $destination = $filesToPatch[$template]
        if (Test-Path $template) {
            # Copy template to destination
            Copy-Item -Path $template -Destination $destination -Force
            # Read the file once, perform both replacements, and write it back
            (Get-Content -Path $destination -Raw) -creplace 'RELEASE', $release -creplace 'SNAPSHOT', $version | Set-Content -Path $destination
        } else {
            Write-Warning "Template file not found, skipping: $template"
        }
    }
} else {
    Write-Error "Could not determine version or release. Aborting."
    exit 1
}
